version: "3.9"
services:
  api:
    build: ./api
    environment:
      - RAWG_API_KEY=${RAWG_API_KEY}
      - TRACK_INTERVAL_MINUTES=60
    volumes:
      - ./api:/app
      - ./data:/app/data
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./web:/app
    ports:
      - "5173:5173"
    command: ["npm","run","dev"]
