name: Publish ZIPs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare scripts
        run: |
          chmod +x ./scripts/publish-zips.sh

      - name: Build ZIP artifacts
        run: ./scripts/publish-zips.sh ${{ github.repository_owner }} ${{ github.event.repository.name }} latest .
        shell: bash

      - name: Upload to GitHub Release (latest)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: artifacts/*.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload workflow run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gamevault-zips
          path: artifacts/*.zip
